# Generated by Django 5.1.5 on 2025-01-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_empresa', models.CharField(max_length=20)),
                ('nr_nivel', models.IntegerField()),
                ('cd_conta_sup', models.CharField(max_length=20)),
                ('ds_titulo_sup', models.CharField(max_length=255)),
                ('cd_classif_contab', models.CharField(max_length=20)),
                ('cd_conta_reduz', models.CharField(max_length=20)),
                ('ds_conta', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'raw_plano_conta',
            },
        ),
        migrations.CreateModel(
            name='ContaContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_empresa', models.CharField(max_length=20)),
                ('cd_estabelecimento', models.CharField(max_length=20)),
                ('classificacao_conta', models.CharField(max_length=50)),
                ('cod_conta_contabil', models.CharField(max_length=50)),
                ('descricao_conta_contabil', models.CharField(max_length=255)),
                ('cod_centro_custo', models.CharField(max_length=50)),
                ('desc_centro_custo', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('valor_realizado', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'raw_conta_contabil',
            },
        ),
    ]
