# Generated by Django 5.1.5 on 2025-01-22 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_modelforecastemployment_stagingcontageral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagingcontageral',
            name='cd_estabelecimento',
        ),
        migrations.RemoveField(
            model_name='stagingcontageral',
            name='classificacao_conta',
        ),
        migrations.RemoveField(
            model_name='stagingcontageral',
            name='cod_centro_custo',
        ),
        migrations.RemoveField(
            model_name='stagingcontageral',
            name='cod_conta_contabil',
        ),
        migrations.RemoveField(
            model_name='stagingcontageral',
            name='desc_centro_custo',
        ),
        migrations.RemoveField(
            model_name='stagingcontageral',
            name='descricao_conta_contabil',
        ),
    ]
