# Generated by Django 5.1.5 on 2025-01-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_stagingcontageral_cd_estabelecimento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StagingContaGeral',
        ),
        migrations.AddField(
            model_name='modelforecastemployment',
            name='nr_nivel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='modelforecastemployment',
            table='staging_forecast_employment',
        ),
    ]
