# Generated by Django 5.1.5 on 2025-01-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_stagingcontageral_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelforecastemployment',
            name='nr_nivel',
        ),
        migrations.AddField(
            model_name='modelforecastemployment',
            name='cd_estabelecimento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
