# Generated by Django 5.1.5 on 2025-01-22 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_modelforecastemployment_nr_nivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelforecastemployment',
            name='cd_estabelecimento',
        ),
    ]
