# Generated by Django 5.1.5 on 2025-01-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_modelforecastccusto'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariacaoDolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'variacao_dolar',
            },
        ),
    ]
