# Generated by Django 5.1.5 on 2025-01-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_variacaodolar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variacaodolar',
            name='valor',
        ),
        migrations.AddField(
            model_name='variacaodolar',
            name='valor_dolar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='variacaodolar',
            name='variacao_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
