# Generated by Django 5.1.5 on 2025-01-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_variacaodolar_valor_variacaodolar_valor_dolar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelforecastccusto',
            name='valor_planejado_mes_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='modelforecastccusto',
            name='valor_planejado_mes_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='modelforecastccusto',
            name='valor_planejado_mes_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='modelforecastccusto',
            name='valor_planejado_mes_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='modelforecastccusto',
            name='valor_planejado_mes_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='modelforecastccusto',
            name='valor_planejado_mes_6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
